name: build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          #username: jenkins-arvato
          #password: ${{ secrets.CR_PAT }}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}          
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: ghcr.io/arvatoaws-labs/db-dumper:latest
          cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/db-dumper:latest
          cache-to: type=inline
